name: Build Next.js Docker Image on VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/startpay"

      - name: Build Docker image on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # timeout: 300
          script: |
            cd ~/startpay
            # sudo chown -R $USER:$USER .
            docker build -t startpay:latest .
            docker stop startpay || true
            docker rm startpay || true
            docker run -d --name startpay --network traefik-net \
              -l "traefik.enable=true" \
              -l "traefik.http.routers.startpay.rule=Host(\"startpay.yeshilab.com\")" \
              -l "traefik.http.routers.startpay.entrypoints=websecure" \
              -l "traefik.http.routers.startpay.tls=true" \
              -l "traefik.http.routers.startpay.tls.certresolver=leresolver" \
              -l "traefik.http.routers.startpay.service=next-service" \
              -l "traefik.http.services.next-service.loadbalancer.server.port=3001" \
              startpay:latest
